{% include 'bread_crumbs.html' %}
<div class="container" style="margin: 30px auto">
    <h1>Регистрация пользователя</h1>
    <div class="register">
        <form action="add/" method="post">
            <p><i>Please fill the form to registrate your account </i><em>*</em></p>
            <fieldset>
                <legend>Registration</legend>
                <label for="reg-login">login<em>*</em></label>
                <input name="reg-login" id="reg-login" placeholder="login" autofocus required pattern="\S+[A-z]"><br>
                <label for="reg-pass">Password <em>*</em></label>
                <input name="reg-pass" id="reg-pass" type="password" placeholder="4[gB33g.0d,Ryd-d!" required
                       pattern="[^\s]{6,30}"><br>
                <label for="pass2">Repeat password</label>
                <input name="pass2" id="pass2" type="password" placeholder="4[gB33g.0d,Ryd-d!" required
                       pattern="[^\s]{6,30}"><br>
            </fieldset>
            <fieldset>
                <legend>Contact info</legend>
                <label for="surname">Surname<em>*</em></label>
                <input name="surname" id="surname" placeholder="Ivanov" autofocus required pattern="\S+[A-za-z]"><br>
                <label for="name">Name <em>*</em></label>
                <input name="name" id="name" placeholder="Ivan" required pattern="\S+[A-za-z]"><br>
                <label for="patronymic">Patronymic</label>
                <input name="patronymic" id="patronymic" placeholder="Ivanovich" pattern="\S+[A-za-z]"><br>
                <label for="telephone">Phone <em>*</em></label>
                <input name="telephone" id="telephone" placeholder="+7-903-955-55-55" required><br>
                <label for="email">Email <em>*</em></label>
                <input name="email" id="email" placeholder="email@server.com" required pattern="\S+@[a-z]+.[a-z]+"><br>
            </fieldset>
            <fieldset>
                <legend>Personal info</legend>
                <label for="age">Age<em>*</em></label> <input name="age" id="age" type="number" required min="14"
                                                              max="100"><br>
                <label for="gender">Sex <em>*</em></label>
                <select name="gender" id="gender">
                    <option value="male">Male</option>
                    <option value="female">Female</option>
                </select><br>
                <label for="comments">About yourself</label>
                <textarea name="comments" id="comments"></textarea>
            </fieldset>
            <p><input type="submit" value="Apply"></p>
        </form>
    </div>
</div>